name: doc_rag

services:

  qdrant:
    image: qdrant/qdrant:latest
    container_name: doc_qdrant
    ports:
      - "6335:6333"
      - "6336:6334"
    volumes:
      - doc_qdrant_storage:/qdrant/storage
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: doc_backend
    ports:
      - "8001:8000"
    environment:
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - OLLAMA_HOST=host.docker.internal
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llama3.2:3b
      - EMBED_MODEL=all-MiniLM-L6-v2
    depends_on:
      - qdrant
    volumes:
      - ./backend:/app
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: doc_frontend
    ports:
      - "8502:8501"
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
    restart: unless-stopped

volumes:
  doc_qdrant_storage:
